# https://github.com/caksoylar/keymap-drawer

layout: {ortho_layout: {split: true, rows: 3, columns: 5, thumbs: 2}}
layers:
  BASE:
    - [Q, W, F, P, B, J, L, U, Y, "'"]
    - [{h: Shift, t: A}, {h: Alt, t: R}, {h: Ctrl, t: S}, {h: Gui, t: T}, G, M, {h: Gui, t: N}, {h: Ctrl, t: E}, {h: Alt, t: I}, {h: Shift, t: O}]
    - [Z, X, C, D, V, K, H, {s: ;, t: ","}, {s: ":", t: .}, {s: \, t: /}]
    - [{h: Ctrl, t: Space}, Shift, NAV, SYM]
  SYM:
    - ["!", "@", "#", "$", "%", "^", "&", "*", "|", "?"]
    - ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]
    - ["+", "=", {s: "[", t: "{"}, {s: "]", t: "}"}, {s: "`", t: "~"}, "!", {s: "<", t: "("}, {s: "<", t: ")"}, "-", "_"]
    - [null, null, null, {type: held}]
  FN:
    - ["BT Clear", F1, F2, F3, null, null, F7, F8, F9, null]
    - [null, F4, F5, F6, "Vol+", "Bri+", F10, F11, F12, null]
    - [BT1, BT2, BT3, null, "Vol-", "Bri-", null, null, null, null]
    - [null, null, null, null]
  NAV:
    - [ESC, null, null, null, null, null, ESC, TAB, DEL, BSPC]
    - [Shift, Alt, Ctrl, Gui, null, Left, Down, Up, Right, Enter]
    - [FN, GAME, null, null, null, Home, PgDN, PgUp, End, null]
    - [null, null, {type: held}, null]
  # VIM:
  #   - [null, null, null, null, null, null, null, null, null, null]
  #   - [null, null, null, null, null, null, null, null, null, null]
  #   - [null, null, null, null, null, null, null, null, null, null]
  #   - [null, null, null, null]
combos:
  - {p: [12, 13], k: "ESC", l: ["BASE"]}
  - {p: [11, 12], k: "TAB", l: ["BASE"]}
  - {p: [16, 17], k: "ESC", l: ["BASE"]}
  - {p: [17, 18], k: "Enter", l: ["BASE"]}
